/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
   import flash.display.Sprite;
   
   import flexUnitTests.GraffitiTouchSuite;
   import flexUnitTests.InteractionInstanceTest;
   import flexUnitTests.InteractiveInstanceObjectPoolTest;
   import flexUnitTests.GraffitiCanvasTest;
   
   public class FlexUnitCompilerApplication extends Sprite
   {
      private var flexUnitTests_GraffitiCanvasTest_obj:flexUnitTests.GraffitiCanvasTest;
      private var flexUnitTests_InteractiveInstanceObjectPoolTest_obj:flexUnitTests.InteractiveInstanceObjectPoolTest;
      private var flexUnitTests_InteractionInstanceTest_obj:flexUnitTests.InteractionInstanceTest;
      
      private var flexUnitTests_InteractionSuite_obj:flexUnitTests.GraffitiTouchSuite;
   }
}