/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
   import flash.display.Sprite;
   
   import GraffitiTouchUnitTests.GraffitiTouchSuite;
   import GraffitiTouchUnitTests.InteractionInstanceTest;
   import GraffitiTouchUnitTests.InteractiveInstanceObjectPoolTest;
   import GraffitiTouchUnitTests.GraffitiCanvasTest;
   import GraffitiTouchUnitTests.RoundBrushTest;
   
   public class FlexUnitCompilerApplication extends Sprite
   {
      private var flexUnitTests_RoundBrushTest_obj:GraffitiTouchUnitTests.RoundBrushTest;
      private var flexUnitTests_GraffitiCanvasTest_obj:GraffitiTouchUnitTests.GraffitiCanvasTest;
      private var flexUnitTests_InteractiveInstanceObjectPoolTest_obj:GraffitiTouchUnitTests.InteractiveInstanceObjectPoolTest;
      private var flexUnitTests_InteractionInstanceTest_obj:GraffitiTouchUnitTests.InteractionInstanceTest;  
      private var flexUnitTests_InteractionSuite_obj:GraffitiTouchUnitTests.GraffitiTouchSuite;
   }
}